import os
import joblib

MODEL_PATH = "models/text_detector_model.pkl"
VECTORIZER_PATH = "models/text_vectorizer.pkl"

AI_KEYWORDS = [
    "as an ai language model",
    "chatgpt",
    "openai",
    "generated by ai",
    "artificial intelligence model",
    "large language model"
]

def predict_text(text):
    text_lower = text.lower().strip()

    if len(text_lower) < 20:
        return {
            "score": 30,
            "label": "Weak Suspicious",
            "reason": "Text is too short for reliable detection."
        }

    for word in AI_KEYWORDS:
        if word in text_lower:
            return {
                "score": 100,
                "label": "Fake",
                "reason": f"AI keyword found in text: {word}"
            }

    if os.path.exists(MODEL_PATH) and os.path.exists(VECTORIZER_PATH):
        model = joblib.load(MODEL_PATH)
        vectorizer = joblib.load(VECTORIZER_PATH)

        x = vectorizer.transform([text])
        prob_fake = float(model.predict_proba(x)[0][1])
        score = int(prob_fake * 100)

        if score >= 70:
            label = "Fake"
        elif score >= 40:
            label = "Suspicious"
        else:
            label = "Normal"

        return {
            "score": score,
            "label": label,
            "reason": "Text ML model prediction."
        }

    return {
        "score": 20,
        "label": "Normal",
        "reason": "No direct AI keyword found. ML model not trained yet."
    }